name: qdContributionsAPI

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        name: Read Iterable -> codarea.json
        run: |
          echo "value=$(jq -c . < ./api/ro/codarea.json)" >> $GITHUB_OUTPUT
      - run: |
          echo '${{ fromJson(steps.matrix.outputs.value) }}'
