name: qdContributionsAPI

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.codarea }}
    steps:
      - name: Read Iterable -> codarea.json
        id: matrix
      - run: echo "codarea=$(jq -c . < ./api/ro/codarea.json)" >> $GITHUB_OUTPUT
      - run: echo '${{ fromJson(steps.matrix.outputs.codarea) }}'
