name: qdContributionsAPI

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.response }}
    steps:
      - name: Make Request 
        id: matrix
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://queridodiario.ok.org.br/api/cities?levels="
      - name: Show Response
        run: |
          echo ${{ steps.matrix.outputs.response }}
          echo ${{ steps.matrix.outputs.headers }}
          echo ${{ steps.matrix.outputs.status }}
          echo ${{ fromJson(steps.matrix.outputs.response).cities }}
  
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        response: ${{fromJSON(needs.setup.outputs.matrix).cities}}
    steps:
      - run: |
          echo "${{ matrix.response }}"

