name: qdContributionsAPI

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo "value=[\"a\", \"b\", \"c\"]" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"
      - name: run curl
        run: | 
          qdCities=$(curl -s --request GET \
          --url https://queridodiario.ok.org.br/api/cities?levels= \
          --header 'content-type: application/json' \
          jq -r '.cities'); echo "qdCities=$qdCities" >> $GITHUB_OUTPUT
    


